---@meta
BoardPointsDisplay = modRequire("scripts.objects.BoardPointsDisplay")
BoardEvent = modRequire("scripts.objects.boardevent")
BoardScoreBar = modRequire("scripts.objects.BoardScoreBar")
BoardHealthBar = modRequire("scripts.objects.BoardHealthBar")
BoardTextbox = modRequire("scripts.objects.BoardTextbox")
BoardWorld = modRequire("scripts.objects.BoardWorld")
BoardUI = modRequire("scripts.objects.BoardUI")
BoardPlayer = modRequire("scripts.objects.BoardPlayer")
BoardScoreAdder = modRequire("scripts.objects.BoardScoreAdder")
BoardInventoryBar = modRequire("scripts.objects.BoardInventoryBar")
BoardSmokePuff = modRequire("scripts.objects.BoardSmokePuff")
